#' Hierarchical Cluster Analysis
#' 
#' Performs hierarchical cluster analysis on a distance matrix generated by 
#' the dist() function. This function reads the distance matrix and item names
#' from the DIST output files and creates a dendrogram.
#'
#' @param notu Number of operational taxonomic units (items) in the dataset
#' @param method The agglomeration method to be used. This should be one of 
#'   "ward.D", "ward.D2", "single", "complete", "average" (= UPGMA), "mcquitty" 
#'   (= WPGMA), "median" (= WPGMC) or "centroid" (= UPGMC). Default is "average".
#'
#' @return Invisibly returns the hclust object
#' @export
#'
#' @examples
#' \dontrun{
#' # First generate a distance matrix
#' delta <- load_delta("chars", "items", "specs")
#' dist(delta)
#' 
#' # Then perform cluster analysis
#' cluster(delta$get_items_nb())
#' cluster(delta$get_items_nb(), method = "complete")
#' }
cluster <- function (notu, method = "average") {
  # Validate input
  if (!is.numeric(notu) || notu <= 0 || notu != round(notu)) {
    stop("'notu' must be a positive integer")
  }
  
  # Check if distance matrix files exist
  if (!file.exists("dist.dis")) {
    stop("Distance matrix file 'dist.dis' not found. Run dist() first.")
  }
  if (!file.exists("dist.nam")) {
    stop("Item names file 'dist.nam' not found. Run dist() first.")
  }	

  # Read distance matrix
  # The dist.dis file contains the lower triangular values (including diagonal)
  mat <- matrix(0, notu, notu)
  mat[row(mat) >= col(mat)] <- scan("dist.dis")
  
  # Read item names and assign to matrix
  names <- scan("dist.nam", what = "character")
  colnames(mat) <- names
  
  # Convert to distance object
  df.dist <- as.dist(mat)
  
  # Perform hierarchical clustering
  hc <- hclust(df.dist, method = method)
  dc <- cophenetic(hc)
  r <- cor(df.dist, dc)
  
  # Plot dendrogram
  par(mar = c(5, 4, 4, 10) + 0.1)
  plot(
    as.dendrogram(hc),
    xlab = "Distance",
    ylab = "OTU's",
    main = paste("Dendrogram", "(r = ", format(r, digits = 4), ")"),
    horiz = TRUE,
    edgePar = list(col = "blue", lwd = 3)
  )
  
  message("Cluster analysis completed successfully")
  message("  - Cophenetic correlation: ", format(r, digits = 4))
  
  invisible(hc)
}